//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admin_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Order
    {
        public string id_detail_history { get; set; }
        public string id_history { get; set; }
        public string name_product { get; set; }
        public string price_product { get; set; }
        public int count { get; set; }
        public string image { get; set; }
        public string id_product { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }


    }
}
